services:
  - type: web
    name: class-tracker-backend
    env: node
    plan: starter
    buildCommand: |
      npm install
      pip install -r requirements.txt
      # Install Chrome dependencies
      apt-get update && apt-get install -y \
        wget \
        gnupg \
        unzip \
        curl \
        xvfb \
        libxi6 \
        libgconf-2-4 \
        default-jdk \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libdrm2 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        ca-certificates \
        fonts-liberation \
        libappindicator1 \
        libnss3 \
        lsb-release \
        xdg-utils \
        libvulkan1
      # Install Chrome
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
      apt-get update
      apt-get install -y google-chrome-stable
      # Install ChromeDriver
      CHROMEDRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
      mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION
      curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/LATEST_RELEASE/chromedriver_linux64.zip
      unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION
      rm /tmp/chromedriver_linux64.zip
      chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver
      ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISPLAY
        value: ":99"